[build]
command = """
composer install --no-dev --optimize-autoloader &&
npm install &&
npm run build &&
php artisan migrate --force
"""

[start]
command = "php artisan serve --host=0.0.0.0 --port=8080"
